# Generated by Django 5.2 on 2025-06-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('screen_repair', 'Screen Repair'), ('battery_replacement', 'Battery Replacement'), ('water_damage', 'Water Damage Repair'), ('malware_removal', 'Malware Removal'), ('board_repair', 'Board Repair'), ('data_recovery', 'Data Recovery'), ('camera_repair', 'Camera Repair'), ('speaker_repair', 'Speaker Repair'), ('charging_port_repair', 'Charging Port Repair')], max_length=50),
        ),
    ]
