# Generated by Django 5.2 on 2025-06-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('screen_repair', 'Screen Repair'), ('battery_replacement', 'Battery Replacement'), ('water_damage', 'Water Damage Repair'), ('malware_removal', 'Malware Removal'), ('board_repair', 'Board Repair'), ('data_recovery', 'Data Recovery'), ('phone_check_up', 'Phone Check Up'), ('hardware_upgrade', 'Hardware Upgrade'), ('hardware_replacement', 'Hardware Replacement')], max_length=50),
        ),
    ]
